#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Preview the legacy Markdown parser and export dated MCP requests. Never pushes automatically.

Usage: python coros_push_plan.py plan.md --export-mcp requests.json

The old parser infers some segments: review before any explicit MCP push.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from coros_client import CorosClient, format_pace, format_duration


# ── Data Models ────────────────────────────────────────────────────

@dataclass
class RunSegment:
    """A single segment of a running workout."""
    role: str           # 'warmup', 'main', 'cooldown', 'fast', 'recovery'
    distance_km: float
    pace_sec: int       # seconds per km
    pace_max_sec: int = 0
    display_name: str = ""

    def __post_init__(self):
        if not self.pace_max_sec:
            self.pace_max_sec = self.pace_sec + 10
        if not self.display_name:
            names = {
                "warmup": "热身", "cooldown": "放松", "main": "训练",
                "fast": "快跑", "recovery": "慢跑",
            }
            self.display_name = names.get(self.role, "训练")


@dataclass
class DailyWorkout:
    """Parsed daily training prescription."""
    day_number: int             # 1-7 (Mon-Sun)
    weekday: str                # 周一..周日
    date: str                   # YYYY-MM-DD
    training_type: str          # 轻松跑, 节奏跑, 间歇, 长距离, 休息, etc.
    total_distance_km: float = 0.0
    pace_str: str = ""          # e.g. "5'30"/km"
    pace_sec: int = 0
    pace_max_sec: int = 0
    training_desc: str = ""     # full training description
    hr_cap: int = 0
    rpe: int = 0
    segments: list[RunSegment] = field(default_factory=list)
    skip: bool = False          # True for rest/cross-training days
    skip_reason: str = ""

    @property
    def coros_name(self) -> str:
        """Generate COROS workout name."""
        type_abbr = {
            "轻松跑": "E跑", "恢复跑": "E跑", "长距离": "LSD",
            "节奏跑": "T跑", "间歇": "I跑", "间歇跑": "I跑",
        }
        abbr = type_abbr.get(self.training_type, self.training_type)
        dist = f"{self.total_distance_km:.0f}km" if self.total_distance_km else ""
        return f"{self.weekday} {abbr} {dist}".strip()

    @property
    def coros_overview(self) -> str:
        """Generate COROS workout description."""
        parts = []
        for seg in self.segments:
            dist = f"{seg.distance_km:.1f}km" if seg.distance_km else ""
            pace = format_pace(seg.pace_sec)
            parts.append(f"{seg.display_name} {dist}@{pace}")
        return " → ".join(parts) if parts else self.training_desc[:100]


# ── Pace Parsing ───────────────────────────────────────────────────

def parse_pace(pace_str: str) -> int:
    """Parse pace string to seconds per km.

    Handles: "5'30\"/km", "5'30\"", "5:30/km", "5:30", "330"
    Returns 0 if unparseable.
    """
    if not pace_str:
        return 0
    pace_str = pace_str.strip()
    # Raw seconds
    if re.fullmatch(r"\d+", pace_str):
        return int(pace_str)
    # M'SS or M:SS patterns
    m = re.search(r"(\d+)\s*[''′:]\s*(\d{1,2})", pace_str)
    if m:
        return int(m.group(1)) * 60 + int(m.group(2))
    return 0


def parse_pace_range(pace_str: str) -> tuple[int, int]:
    """Parse pace range like "5'20\"-5'40\"/km" or single pace.

    Returns (pace_min_sec, pace_max_sec). min = faster, max = slower.
    """
    if not pace_str:
        return 0, 0
    # Range pattern: "X'XX" - Y'YY" or "X'XX"~Y'YY" or "X'XX"-Y'YY"
    parts = re.split(r'[\s]*[-–~至到][\s]*', pace_str, maxsplit=1)
    if len(parts) == 2:
        p1 = parse_pace(parts[0])
        p2 = parse_pace(parts[1])
        if p1 and p2:
            return (min(p1, p2), max(p1, p2))
    p = parse_pace(pace_str)
    return (p, p + 10) if p else (0, 0)


# ── Markdown Parser ────────────────────────────────────────────────

def parse_weekly_plan(md_path: str) -> list[DailyWorkout]:
    """Parse a weekly training plan Markdown file.

    Extracts Day 1-7 training prescriptions from the standard format
    generated by training-weekly skill.

    Args:
        md_path: Path to the *_W*_训练计划.md file.

    Returns:
        List of 7 DailyWorkout objects (some may have skip=True).
    """
    text = Path(md_path).read_text(encoding="utf-8")
    workouts: list[DailyWorkout] = []

    # Split into daily sections by "### Day N:" headers
    day_pattern = re.compile(
        r'^###\s+Day\s+(\d+)\s*[:：]\s*(周[一二三四五六日])\s+'
        r'(\d{4}-\d{2}-\d{2})\s*[—–-]\s*(.+?)$',
        re.MULTILINE,
    )
    matches = list(day_pattern.finditer(text))

    for i, match in enumerate(matches):
        day_num = int(match.group(1))
        weekday = match.group(2)
        date = match.group(3)
        training_type = match.group(4).strip()

        # Extract section text until next Day header or end
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        section = text[start:end]

        workout = DailyWorkout(
            day_number=day_num,
            weekday=weekday,
            date=date,
            training_type=training_type,
        )

        # Check if rest / cross-training day
        rest_keywords = ["休息", "完全休息", "交叉训练", "瑜伽", "游泳", "骑车"]
        if any(kw in training_type for kw in rest_keywords):
            workout.skip = True
            workout.skip_reason = training_type
            workouts.append(workout)
            continue

        # Parse table rows for structured fields
        _parse_table_fields(section, workout)

        # Build COROS segments from parsed data
        _build_segments(workout)

        workouts.append(workout)

    return workouts


def _parse_table_fields(section: str, workout: DailyWorkout) -> None:
    """Extract fields from the daily training table."""
    table_row = re.compile(
        r'^\|\s*\*{0,2}(.+?)\*{0,2}\s*\|\s*(.+?)\s*\|',
        re.MULTILINE,
    )
    for m in table_row.finditer(section):
        key = m.group(1).strip().strip("*")
        val = m.group(2).strip()

        if key == "类型":
            if not workout.training_type or workout.training_type == val:
                workout.training_type = val
        elif key == "训练":
            workout.training_desc = val
        elif key == "距离":
            dist_m = re.search(r'([\d.]+)\s*km', val)
            if dist_m:
                workout.total_distance_km = float(dist_m.group(1))
        elif key == "配速":
            workout.pace_str = val
            p_min, p_max = parse_pace_range(val)
            workout.pace_sec = p_min
            workout.pace_max_sec = p_max
        elif key == "心率":
            hr_m = re.search(r'(\d+)\s*bpm', val)
            if hr_m:
                workout.hr_cap = int(hr_m.group(1))
        elif key == "RPE":
            rpe_m = re.search(r'(\d+)', val)
            if rpe_m:
                workout.rpe = int(rpe_m.group(1))


def _build_segments(workout: DailyWorkout) -> None:
    """Build COROS running segments from the parsed workout data."""
    if workout.skip or workout.total_distance_km <= 0:
        workout.skip = True
        workout.skip_reason = workout.skip_reason or "无跑步距离"
        return

    if not workout.pace_sec:
        workout.skip = True
        workout.skip_reason = "无法解析配速"
        return

    tt = workout.training_type

    # Detection order: easy/long first (most common), then interval, then tempo
    if _is_easy_or_long(tt, workout.training_desc):
        _build_easy_segments(workout)
    elif _is_interval(tt, workout.training_desc):
        _build_interval_segments(workout)
    elif _is_tempo(tt, workout.training_desc):
        _build_tempo_segments(workout)
    else:
        # Default: treat as easy run
        _build_easy_segments(workout)


def _is_easy_or_long(training_type: str, desc: str) -> bool:
    """Detect easy/recovery/long runs (highest priority — most common)."""
    type_lower = training_type.lower()
    easy_keywords = [
        "轻松跑", "恢复跑", "easy", "recovery", "长距离", "long",
        "lsd", "慢跑", "有氧跑", "大步跑",
    ]
    return any(kw in type_lower for kw in easy_keywords)


def _is_interval(training_type: str, desc: str) -> bool:
    keywords = ["间歇", "interval", "亚索", "yasso", "变速", "fartlek"]
    combined = (training_type + " " + desc).lower()
    return any(kw in combined for kw in keywords)


def _is_tempo(training_type: str, desc: str) -> bool:
    """Detect tempo runs. Checks type strictly (desc may contain '节奏' in other contexts)."""
    keywords = ["节奏跑", "tempo", "乳酸阈", "threshold", "巡航间歇"]
    type_lower = training_type.lower()
    return any(kw in type_lower for kw in keywords)


def _build_easy_segments(workout: DailyWorkout) -> None:
    """Build warmup + main + cooldown for easy/long runs."""
    total = workout.total_distance_km
    pace = workout.pace_sec
    pace_max = workout.pace_max_sec

    if total <= 4:
        # Short run: single main segment, no warmup/cooldown
        workout.segments = [
            RunSegment("main", total, pace, pace_max, "训练"),
        ]
    else:
        # Standard: 1km warmup (slower) + main + 1km cooldown (slower)
        warmup_km = 1.0
        cooldown_km = 1.0
        main_km = total - warmup_km - cooldown_km

        warmup_pace = pace + 20  # ~20s/km slower
        cooldown_pace = pace + 30

        workout.segments = [
            RunSegment("warmup", warmup_km, warmup_pace, warmup_pace + 10, "热身"),
            RunSegment("main", main_km, pace, pace_max, "训练"),
            RunSegment("cooldown", cooldown_km, cooldown_pace, cooldown_pace + 10, "放松"),
        ]


def _build_tempo_segments(workout: DailyWorkout) -> None:
    """Build warmup + tempo main + cooldown for tempo runs."""
    total = workout.total_distance_km
    pace = workout.pace_sec
    pace_max = workout.pace_max_sec

    # Try to parse structured description: "热身 Xkm → 主课 Ykm @ T-Pace → 冷身 Zkm"
    desc = workout.training_desc
    struct_m = re.search(
        r'热身\s*([\d.]+)\s*km.*?'
        r'(?:主课|节奏|T[- ]?Pace)\s*([\d.]+)\s*km.*?'
        r'(?:冷身|放松)\s*([\d.]+)\s*km',
        desc, re.IGNORECASE,
    )
    if struct_m:
        warmup_km = float(struct_m.group(1))
        main_km = float(struct_m.group(2))
        cooldown_km = float(struct_m.group(3))
    else:
        warmup_km = min(2.0, total * 0.2)
        cooldown_km = min(2.0, total * 0.2)
        main_km = total - warmup_km - cooldown_km

    e_pace = pace + 60  # E-pace ~60s slower than T-pace

    workout.segments = [
        RunSegment("warmup", warmup_km, e_pace, e_pace + 10, "热身"),
        RunSegment("main", main_km, pace, pace_max, "节奏跑"),
        RunSegment("cooldown", cooldown_km, e_pace + 10, e_pace + 20, "放松"),
    ]


def _build_interval_segments(workout: DailyWorkout) -> None:
    """Build warmup + N×(fast+recovery) + cooldown for interval workouts."""
    total = workout.total_distance_km
    pace = workout.pace_sec
    desc = workout.training_desc

    # Try to parse interval structure from description
    # Patterns: "N × Xm", "N × X.Xkm", "NxXm", "400m×6-8组"
    rep_m = re.search(
        r'(\d+)\s*[×xX]\s*([\d.]+)\s*(m|km)', desc, re.IGNORECASE,
    )
    reps = 0
    rep_dist_km = 0.0
    if rep_m:
        reps = int(rep_m.group(1))
        dist_val = float(rep_m.group(2))
        unit = rep_m.group(3).lower()
        rep_dist_km = dist_val if unit == "km" else dist_val / 1000
    elif re.search(r'([\d.]+)\s*(m|km)\s*[×xX]\s*(\d+)', desc, re.IGNORECASE):
        alt_m = re.search(
            r'([\d.]+)\s*(m|km)\s*[×xX]\s*(\d+)', desc, re.IGNORECASE)
        dist_val = float(alt_m.group(1))
        unit = alt_m.group(2).lower()
        reps = int(alt_m.group(3))
        rep_dist_km = dist_val if unit == "km" else dist_val / 1000

    if not reps or not rep_dist_km:
        # Fallback: treat as tempo run if can't parse interval structure
        _build_tempo_segments(workout)
        return

    # Parse recovery distance (default: equal to rep distance for short, half for long)
    recovery_dist_km = rep_dist_km if rep_dist_km <= 0.5 else rep_dist_km * 0.5

    # Calculate warmup/cooldown
    interval_total = reps * (rep_dist_km + recovery_dist_km)
    remaining = total - interval_total
    warmup_km = max(1.0, remaining * 0.5)
    cooldown_km = max(1.0, remaining - warmup_km)

    # E-pace for warmup/cooldown/recovery (~60s slower than I-pace)
    e_pace = pace + 80

    segments = [
        RunSegment("warmup", warmup_km, e_pace, e_pace + 10, "热身"),
    ]

    for i in range(reps):
        segments.append(
            RunSegment("fast", rep_dist_km, pace, pace + 5, "快跑")
        )
        # No recovery after last rep
        if i < reps - 1:
            segments.append(
                RunSegment("recovery", recovery_dist_km, e_pace, e_pace + 20, "慢跑")
            )

    segments.append(
        RunSegment("cooldown", cooldown_km, e_pace + 10, e_pace + 20, "放松")
    )

    workout.segments = segments


# ── COROS Push Logic ───────────────────────────────────────────────

def mcp_request(workout):
    if not workout.segments:
        raise ValueError("No workout sections; inspect the source plan")
    sections = []
    for seg in workout.segments:
        if seg.distance_km <= 0 or not 120 <= seg.pace_sec <= 1499 or not 120 <= seg.pace_max_sec <= 1499:
            raise ValueError("Unsupported distance or pace; review the workout")
        sections.append({
            "sectionType": {"warmup": 1, "cooldown": 4, "recovery": 3}.get(seg.role, 2),
            "targetType": 1, "targetValue": round(seg.distance_km * 1000),
            "intensityType": 2, "intensityValueStart": seg.pace_sec,
            "intensityValueEnd": seg.pace_max_sec,
        })
    return {"tool": "createScheduledWorkout", "arguments": {
        "date": workout.date.replace("-", ""),
        "course": {"sportType": 1, "courseName": workout.coros_name,
                   "courseDescription": workout.coros_overview + "；各段按实际配速范围执行。",
                   "sections": sections}}}


def main():
    import json
    parser = argparse.ArgumentParser(description="Review a legacy Markdown plan and export dated COROS MCP requests; never auto-push")
    parser.add_argument("plan_file")
    parser.add_argument("--days", default="")
    parser.add_argument("--dry-run", action="store_true", help="Compatibility flag; this command is always a preview")
    parser.add_argument("--export-mcp", help="Save request manifest for review by the runner and MCP host")
    args = parser.parse_args()
    days = {int(n) for n in args.days.split(",")} if args.days else None
    workouts = parse_weekly_plan(args.plan_file)
    if not workouts:
        parser.error("No workouts parsed; do not infer a plan from missing data")
    calls = [mcp_request(w) for w in workouts if not w.skip and (not days or w.day_number in days)]
    manifest = {"schema": "coros-mcp-write-review/v1", "confirmed": False,
                "warning": "Legacy Markdown parser may infer distance, warmup, cooldown and pace. Review every section against the confirmed source plan. Explicit push authorization and read-back are required before execution.",
                "calls": calls}
    text = json.dumps(manifest, ensure_ascii=False, indent=2)
    if args.export_mcp:
        Path(args.export_mcp).write_text(text, encoding="utf-8")
    else:
        print(text)
    print("仅预览，未写入COROS；须先确认具体课表，再明确要求推送。", file=sys.stderr)


if __name__ == "__main__":
    main()
